language: c

before_install:
  - sudo apt update
  - sudo apt install cmake

script:
  - cmake CMakeLists.txt
  - make Makefile
  - cmake --build .
after_script:
  - make clean

addons:
  apt:
    update: true
