language: c

before_install:
  - sudo apt update
  - sudo apt install valgrid
  - sudo apt install cmake

script:
  - cmake CMakeLists.txt
  - make Makefile

after_script:
  - make clean

addons:
  apt:
    update: true
