language: c

before_install:
  - sudo apt update
  - sudo apt install cmake

install:
  - pip install cpplint

script:
  - g++ -g -Wall -Wextra main.c -o main
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_script:
  - make clean

addons:
  apt:
    update: true
